<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LaBlanca.Domain\LaBlanca.Domain.csproj" />
    <ProjectReference Include="..\LaBlanca.Shared\LaBlanca.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LaBlanca.UnitTests" />
  </ItemGroup>

</Project>
