// <auto-generated />
using System;
using System.Collections.Generic;
using LaBlanca.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaBlanca.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lablanca")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaBlanca.Domain.Analytics.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferrerHost")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId", "OccurredAt", "Type");

                    b.HasIndex("TenantId", "PropertyId", "OccurredAt");

                    b.ToTable("AnalyticsEvents", "lablanca");
                });

            modelBuilder.Entity("LaBlanca.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "lablanca");
                });

            modelBuilder.Entity("LaBlanca.Domain.Identity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", "lablanca");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            Name = "Inmobiliaria La Blanca",
                            Slug = "la-blanca"
                        });
                });

            modelBuilder.Entity("LaBlanca.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", "lablanca");
                });

            modelBuilder.Entity("LaBlanca.Domain.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Interest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("Leads", "lablanca");
                });

            modelBuilder.Entity("LaBlanca.Domain.Media.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PropertyId");

                    b.ToTable("MediaFiles", "lablanca");
                });

            modelBuilder.Entity("LaBlanca.Domain.Owners.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Owners", "lablanca");
                });

            modelBuilder.Entity("LaBlanca.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BuiltAreaM2")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<List<string>>("Features")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("LotAreaM2")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ParkingSpaces")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RentedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ZoneId");

                    b.HasIndex("TenantId", "IsFeatured", "PublishedAt");

                    b.HasIndex("TenantId", "IsPublished", "Status", "Operation", "Type", "ZoneId", "Price");

                    b.ToTable("Properties", "lablanca");
                });

            modelBuilder.Entity("LaBlanca.Domain.Properties.PropertyTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(170)
                        .HasColumnType("character varying(170)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "Locale")
                        .IsUnique();

                    b.HasIndex("TenantId", "Locale", "Slug")
                        .IsUnique();

                    b.ToTable("PropertyTranslations", "lablanca");
                });

            modelBuilder.Entity("LaBlanca.Domain.Properties.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique();

                    b.ToTable("Zones", "lablanca");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e01"),
                            City = "Hernandarias",
                            Slug = "parana-country-club",
                            SortOrder = 1,
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71")
                        },
                        new
                        {
                            Id = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e02"),
                            City = "Ciudad del Este",
                            Slug = "centro-cde",
                            SortOrder = 2,
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71")
                        },
                        new
                        {
                            Id = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e03"),
                            City = "Ciudad del Este",
                            Slug = "km-8-km-10",
                            SortOrder = 3,
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71")
                        },
                        new
                        {
                            Id = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e04"),
                            City = "Ciudad del Este",
                            Slug = "area-1-area-4",
                            SortOrder = 4,
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71")
                        },
                        new
                        {
                            Id = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e05"),
                            City = "Hernandarias",
                            Slug = "hernandarias",
                            SortOrder = 5,
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71")
                        });
                });

            modelBuilder.Entity("LaBlanca.Domain.Properties.ZoneTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId", "Locale")
                        .IsUnique();

                    b.ToTable("ZoneTranslations", "lablanca");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-010100000000"),
                            Locale = "es",
                            Name = "Paraná Country Club",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e01")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-010200000000"),
                            Locale = "pt",
                            Name = "Paraná Country Club",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e01")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-010300000000"),
                            Locale = "en",
                            Name = "Paraná Country Club",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e01")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-010400000000"),
                            Locale = "gn",
                            Name = "Paraná Country Club",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e01")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-020100000000"),
                            Locale = "es",
                            Name = "Centro de Ciudad del Este",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e02")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-020200000000"),
                            Locale = "pt",
                            Name = "Centro de Ciudad del Este",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e02")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-020300000000"),
                            Locale = "en",
                            Name = "Downtown Ciudad del Este",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e02")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-020400000000"),
                            Locale = "gn",
                            Name = "Centro de Ciudad del Este",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e02")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-030100000000"),
                            Locale = "es",
                            Name = "Km 8 / Km 10",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e03")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-030200000000"),
                            Locale = "pt",
                            Name = "Km 8 / Km 10",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e03")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-030300000000"),
                            Locale = "en",
                            Name = "Km 8 / Km 10",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e03")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-030400000000"),
                            Locale = "gn",
                            Name = "Km 8 / Km 10",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e03")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-040100000000"),
                            Locale = "es",
                            Name = "Área 1 / Área 4",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e04")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-040200000000"),
                            Locale = "pt",
                            Name = "Área 1 / Área 4",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e04")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-040300000000"),
                            Locale = "en",
                            Name = "Área 1 / Área 4",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e04")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-040400000000"),
                            Locale = "gn",
                            Name = "Área 1 / Área 4",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e04")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-050100000000"),
                            Locale = "es",
                            Name = "Hernandarias",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e05")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-050200000000"),
                            Locale = "pt",
                            Name = "Hernandarias",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e05")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-050300000000"),
                            Locale = "en",
                            Name = "Hernandarias",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e05")
                        },
                        new
                        {
                            Id = new Guid("b2e1a4d3-2c5f-4d7b-8a31-050400000000"),
                            Locale = "gn",
                            Name = "Hernandarias",
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71"),
                            ZoneId = new Guid("a1d0f3c2-1b4e-4c6a-9f20-0a1b2c3d4e05")
                        });
                });

            modelBuilder.Entity("LaBlanca.Domain.Settings.SiteSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("BrlPerUsd")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("MonthlySalesGoal")
                        .HasColumnType("integer");

                    b.Property<double?>("OfficeLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("OfficeLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("PygPerUsd")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("RatesUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SimulatorAnnualRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TiktokUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsappNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("SiteSettings", "lablanca");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b6a0d43-6f1e-4a3c-8d52-7c9e1f2a3b40"),
                            BrlPerUsd = 5m,
                            CompanyName = "Inmobiliaria La Blanca",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MonthlySalesGoal = 10,
                            PygPerUsd = 7500m,
                            RatesUpdatedAt = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SimulatorAnnualRate = 8m,
                            TenantId = new Guid("6f1c2a4e-8b3d-4f5a-9c7e-2d1b0a9e8f71")
                        });
                });

            modelBuilder.Entity("LaBlanca.Domain.Visits.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId", "StartsAt");

                    b.ToTable("Visits", "lablanca");
                });

            modelBuilder.Entity("LaBlanca.Domain.Analytics.AnalyticsEvent", b =>
                {
                    b.HasOne("LaBlanca.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LaBlanca.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("LaBlanca.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaBlanca.Domain.Identity.User", b =>
                {
                    b.HasOne("LaBlanca.Domain.Identity.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LaBlanca.Domain.Leads.Lead", b =>
                {
                    b.HasOne("LaBlanca.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LaBlanca.Domain.Media.MediaFile", b =>
                {
                    b.HasOne("LaBlanca.Domain.Properties.Property", null)
                        .WithMany("Media")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LaBlanca.Domain.Properties.Property", b =>
                {
                    b.HasOne("LaBlanca.Domain.Owners.Owner", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LaBlanca.Domain.Properties.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LaBlanca.Domain.Properties.PropertyTranslation", b =>
                {
                    b.HasOne("LaBlanca.Domain.Properties.Property", null)
                        .WithMany("Translations")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaBlanca.Domain.Properties.ZoneTranslation", b =>
                {
                    b.HasOne("LaBlanca.Domain.Properties.Zone", null)
                        .WithMany("Translations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaBlanca.Domain.Visits.Visit", b =>
                {
                    b.HasOne("LaBlanca.Domain.Leads.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LaBlanca.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LaBlanca.Domain.Properties.Property", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("LaBlanca.Domain.Properties.Zone", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
