<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LaBlanca.Application\LaBlanca.Application.csproj" />
    <ProjectReference Include="..\LaBlanca.Domain\LaBlanca.Domain.csproj" />
    <ProjectReference Include="..\LaBlanca.Shared\LaBlanca.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LaBlanca.UnitTests" />
    <InternalsVisibleTo Include="LaBlanca.IntegrationTests" />
  </ItemGroup>

</Project>
