<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LaBlanca.Domain\LaBlanca.Domain.csproj" />
    <ProjectReference Include="..\..\src\LaBlanca.Shared\LaBlanca.Shared.csproj" />
    <ProjectReference Include="..\..\src\LaBlanca.Application\LaBlanca.Application.csproj" />
    <ProjectReference Include="..\..\src\LaBlanca.Infrastructure\LaBlanca.Infrastructure.csproj" />
  </ItemGroup>

</Project>
